### ISSUE TITLE
msidn duplicate exception

### ISSUE THREAD

**Issue by svoss** [messagebird/php-rest-api#61] opened 2018-02-06 12:37 UTC
I know that this issue might be more related to the API itself but ..

```
<?php
require 'vendor/autoload.php';
$ACCESS_KEY = '';//FILL access key

$c = new \MessageBird\Client($ACCESS_KEY);
$contact = new \MessageBird\Objects\Contact();
$contact->msisdn = "31613371337";
$contact->firstName = "Foo";
$contact->lastName = "Bar";
$contact = $c->contacts->create($contact);


$contact->firstName = "Foo changed";
$c->contacts->update($contact, $contact->getId());
```
This code snippet causes an exception like: 
> contact with this msisdn already exists in your contact list

The system checks if the msidn already exists, but in this case i am just not changing it...

Why? Keeping track if the phone number did or did not change is not very practical in a lot of use cases. I can work around it by always deleting and then adding the contact again but that has some disadvantages.

**Comment by epels** [comment] 2018-07-13 10:35
Hi @svoss, thank you for opening an issue!

I've been able to reproduce this bug: the problem is that the API accepts a HTTP `PATCH` request with a body containing only the fields that are actually being updated.
When you invoke `MessageBirdClient->contacts->update` with an existing object, like you are, it will have the MSISDN set - but you're not updating it. This is why the API returns this error.

While I look for ways to fix this in a clean way, you can work around the issue by unsetting the MSISDN before updating the contact:

```php
$contact = new \MessageBird\Objects\Contact();
$contact->msisdn = "31613371337";
$contact->firstName = "Foo";
$contact->lastName = "Bar";
$contact = $c->contacts->create($contact);

unset($contact->msisdn);

$contact->firstName = "Foo changed";
$c->contacts->update($contact, $contact->getId());
```

Unsetting the lastName does **not** seem to be necessary.

Please let me know if you have any other questions!

**Comment by epels** [comment] 2018-07-25 15:40
Hi @svoss, hopefully you've managed to resolve the problem based on the information above. I'm closing this issue for now: feel free to comment or re-open in case you're still running into problems!

**Closed by epels** 2018-07-25 15:40 UTC
Labels: bug
